package co.pointred.core.startup;

public enum RemotingMsg
{
	// Ping msg to start with
	PING, PONG,
	// modes of Startup
	WHAT_MODE_ARE_YOU_IN, 
	DEFAULT_MODE_I_AM_IN, 
	IDLE_MODE_I_AM_IN,
	INTERMEDIATE_MODE_I_AM_IN,
	
	SECONDARY_GOTO_IDLE_MODE_FOR_RECOVERY, SECONDARY_GONE_TO_IDLE_MODE_FOR_RECOVERY, 
	
	SUSPEND_SECONDARY_PINGER, SECONDARY_PINGER_SUSPENDED,
	SUSPEND_PRIMARY_PINGER, PRIMARY_PINGER_SUSPENDED,
	RESUME_PRIMARY_PINGER, RESUME_SECONDARY_PINGER,
	PRIMARY_PINGER_RESUMED, SECONDARY_PINGER_RESUMED,
	
	PRIMARY_IN_IDLE_RECOVER_SECONDARY_FROM_PRIMARY, SECONDARY_RECOVERED_FROM_PRIMARY,
	RECOVER_PRIMARY_FROM_SECONDARY, PRIMARY_RECOVERED_FROM_SECONDARY,
	
	MARK_SECONDARY_AS_CLEAN,
	MARK_PRIMARY_AS_CLEAN,
	ERROR;
}
