package co.pointred.core.startup;

public enum StartUpMsg
{
	// Ping msg to start with
	PING, PONG,
	WHAT_MODE_ARE_YOU_IN,
	IDLE_MODE_I_AM_IN,
	DEFAULT_MODE_I_AM_IN,
	INTERMEDIATE_MODE_I_AM_IN,
	GOTO_IDLE_MODE_I_WANT_TO_RECOVER,
	GONE_TO_IDLE_MODE_YOU_RECOVER,
	GOTO_DEFAULT_MODE_I_HAVE_RECOVERED,
	GONE_TO_DEFAULT_MODE,
	IS_PRIMARY_DIRTY,
	PRIMARY_IS_NOT_DIRTY,
	PRIMARY_IS_DIRTY,
	
	SUSPEND_PRIMARY_PINGER, PRIMARY_PINGER_SUSPENDED,
	SUSPEND_SECONDARY_PINGER, SECONDARY_PINGER_SUSPENDED,
	RESUME_PRIMARY_PINGER,PRIMARY_PINGER_RESUMED,
	RESUME_SECONDARY_PINGER,SECONDARY_PINGER_RESUMED,
	START_UP_ERROR;

}
