package co.pointred.core.database.replication;

public enum ReplicationEnum
{
	CREATE_OBJECT, UPDATE_OBJECT, DELETE_ROW, DELETE, BULKINSERT_MAP, BULKINSERT_OBJECT, BULKUPDATE_MAP, BULKUPDATE_OBJECT, BULKDELETE_OBJECT,
	CREATE_TX_OBJECT,UPDATE_TX_OBJECT,DELETE_TX_ROW, DELETE_TX,BULKINSERT_TX_OBJECT,BULKINSERT_TX_MAP,BULKUPDATE_TX_OBJECT,BULKUPDATE_TX_MAP,BULKDELETE_TX_OBJECT,
	BEGIN_TX, COMMIT_TX, END_TX,POISON;
}
